### ISSUE TITLE
Maximum call stack size exceeded    

### ISSUE THREAD

**Issue by mnpenner** [scinos/webpack-plugin-hash-output#15]
I get this error as soon as I added `new HashOutput()` to my list of plugins:

```
Unhandled rejection RangeError: Maximum call stack size exceeded        
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:40)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/home/me/Projects/myproject/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
```

My 'compiled' webpack.config looks like this, if you need to see it:

```js
{ target: 'web',
    context: '/home/me/Projects/myproject',
    mode: 'production',
    entry:
    { main:
        [ '/home/me/Projects/myproject/assets/scripts/lib/autofocus-polyfill',
            '/home/me/Projects/myproject/assets/scripts/lib/matches-polyfill',
            'whatwg-fetch',
            'core-js/es6',
            'core-js/stage/4',
            '/home/me/Projects/myproject/assets/main' ],
            print:
        [ '/home/me/Projects/myproject/assets/stylesheets/print' ] },
    output:
    { path: '/home/me/Projects/myproject/www/assets',
        pathinfo: false,
        publicPath: '/assets/',
        crossOriginLoading: 'anonymous',
        filename: '[name].[chunkhash].js',
        chunkFilename: 'chunk.[chunkhash].js' },
    resolve:
    { modules:
        [ '/home/me/Projects/myproject/assets',
            '/home/me/Projects/myproject/node_modules/',
            '/home/me/Projects/myproject/vendor/' ],
            alias:
        { 'jquery-ui/ui/widget': '/home/me/Projects/myproject/node_modules/jquery-ui/widget.js' },
        extensions: [ '.jsx', '.js', '.less', '.css' ] },
    node: { __filename: true, __dirname: true, fs: 'empty' },
    amd: { jQuery: true },
    module:
    { rules:
        [ { enforce: 'pre',
            test: /\.jsx?$/,
            loader: 'eslint-loader',
            include: '/home/me/Projects/myproject/assets',
            options: { cache: false, quiet: true, failOnError: true } },
            { test: /\.jsx?$/,
                loader: 'strip-loader',
                options:
                    { strip:
                            [ 'console.assert',
                                'console.count',
                                'console.dir',
                                'console.dirxml',
                                'console.group',
                                'console.groupCollapsed',
                                'console.groupEnd',
                                'console.info',
                                'console.log',
                                'console.profile',
                                'console.profileEnd',
                                'console.table',
                                'console.time',
                                'console.timeEnd',
                                'console.timeStamp' ] } },
            { test: /\.less$/,
                use:
                    [ '/home/me/Projects/myproject/node_modules/mini-css-extract-plugin/dist/loader.js',
                        { loader: 'css-loader', options: [Object] },
                        { loader: 'postcss-loader', options: [Object] },
                        { loader: 'less-loader', options: [Object] } ] },
            { test: /\.css$/,
                use:
                    [ '/home/me/Projects/myproject/node_modules/mini-css-extract-plugin/dist/loader.js',
                        { loader: 'css-loader', options: [Object] },
                        { loader: 'postcss-loader', options: [Object] } ] },
            { test: /\.jsx?$/,
                include:
                    [ '/home/me/Projects/myproject/assets',
                        '/home/me/Projects/myproject/node_modules/react-ajax-loader' ],
                loader: 'babel-loader',
                options:
                    { cacheDirectory: '/home/me/Projects/myproject/cache/babel',
                        forceEnv: 'production' } },
            { test: /\.(jpe?g|png|gif|svg)($|\?)/i,
                loader: 'url-loader',
                options: { limit: 2048, name: '[name]-[sha1:hash:hex:10].[ext]' } },
            { test: /\.(eot|ttf|woff2?|htc)($|\?)/i,
                loader: 'file-loader',
                options: { name: '[name]-[sha1:hash:hex:10].[ext]' } } ] },
    plugins:
        [ NoEmitOnErrorsPlugin {},
            HashedModuleIdsPlugin {
            options:
                { context: null,
                    hashFunction: 'md4',
                    hashDigest: 'base64',
                    hashDigestLength: 4 } },
            LoaderOptionsPlugin { options: { options: {}, test: { test: [Function: test] } } },
    MiniCssExtractPlugin {
    options:
    { filename: '[name].[hash].css',
        chunkFilename: 'chunk.[chunkhash].css' } },
    ProvidePlugin {
    definitions:
    { '$': 'jquery',
        jQuery: 'jquery',
        timezoneJS: 'timezone-js',
        React: 'react',
        _: 'lodash' } },
    DefinePlugin {
    definitions: { 'process.env': { NODE_ENV: '"production"' } } },
    { apply: [Function: apply] } ],
    bail: true,
        devtool: 'source-map',
    optimization:
    { minimize: true,
        minimizer:
        [ UglifyJsPlugin {
            options:
                { test: /\.(js?)(\?.+)?$/i,
                    warningsFilter: [Function],
                    extractComments: /^!|\b(copyright|license)\b|@(preserve|license|cc_on)\b/i,
                    sourceMap: true,
                    cache: true,
                    parallel: true,
                    include: undefined,
                    exclude: /\.min\.js$/,
                    uglifyOptions:
                        { output: [Object],
                            compress: [Object],
                            mangle: true,
                            sourceMap: true } } } ],
            splitChunks: { chunks: 'all' },
        runtimeChunk: true } }
```

**Comment by scinos** [comment]
I can't reproduce this one :(

* Which version of webpack are you using?
* Can you post the *smallest* webpack config that shows the problem?

**Comment by fi5u** [comment]
I also get the same error with version 2.0.0. Webpack version 4.5.0.

Traceback is as follows:
```
1ms asset optimization
 93% after asset optimization Update chunks(node:39514) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:40)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
    at chunkGroup.getParents.map.parentGroup (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:112:12)
    at Array.map (<anonymous>)
    at getAllParents (/Users/fisu/Projects/yoo/node_modules/webpack-plugin-hash-output/src/OutputHash.js:110:36)
(node:39514) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39514) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by scinos** [comment]
@fi5u can you provide the minimum webpack config to reproduce the issue? Creating a repo with some reproduction steps will be very helpful too.

**Comment by fi5u** [comment]
@scinos In creating a minimal repo, I've discovered that the issue is not due to Webpack config, but rather recursively-called async React components.

A minimal repo reproducing the issue is [here](https://github.com/fi5u/hashoutput-test).

Running `yarn run build:dist`will show the above error with the same traceback.

So in the code, `HomeContainer` calls `MediaBlock` with the prop `callAgain` as `true`. `MediaBlock` asynchronously loads `Media` component, passing the `true` `callAgain` prop. In `Media` component, if `callAgain` is `true`, then asynchronously load `MediaBlock` but don't pass any props.

So this isn't recursing infinitely, the final output should be:
```
<HomeContainer>
  <MediaBlock>
    <Media>
      <MediaBlock>
        <Media />
      </MediaBlock>
    </Media>
  </MediaBlock>
</HomeContainer>
```

Note: when the async calls are replaced with standard imports, the webpack-plugin-hash-output does not error out when compiling.

Hopefully this helps and makes sense.

**Comment by scinos** [comment]
Interesting!
Thanks for the extra details, I'll take a look ASAP

**Comment by scinos** [comment]
Interesting!
Thanks for the extra details, I'll take a look ASAP

**Comment by mnpenner** [comment]
Hi guys, sorry for not responding sooner. Just got back to this.

Thanks for finding and fixing!

I'm trying it now, but it's freezing on

>  93% after asset optimization Update chunks 

I'm not quite sure if it's just *really* slow (my project is rather large) or it's actually stuck. It worked fine on my other bundle.

I tried copying @fi5u's project to see if I could reproduce it there. Thought maybe it was clashing with one of my other plugins, but I can't seem to get it to happen there.

I think my project is probably just too big now. Still frozen after 12 minutes of building. I know that's not very helpful, so don't worry about it :smile:

**Comment by fi5u** [comment]
@scinos It does not produce the same problem as before, but I have the same problem as @mnpenner.
I too have a very large project and it freezes in the same place. When I remove `webpack-plugin-hash-output` the build completes without issue.
Even on the small repo I posted, after upgrading webpack-plugin-hash-output to 2.1.0, it freezes on

> 93% after asset optimization Update chunks

**Comment by salzhrani** [comment]
Samy here. maybe reopen the issue?

**Comment by scinos** [comment]
Raised #16, working on it.

Apologies for the broken version, I'll release a fix ASAP.
